### ISSUE TITLE
When importing 2 react apps, only the second one is shown

### ISSUE THREAD

**Issue by fabpico** [AtenDesignGroup/js_component_examples#27]
Drupal `8.9.19`
js_component `2.0.0-alpha1` | `8.x-1.0-alpha2`
"react": "^16.8.6",
"react-dom": "^16.8.6",
"react-scripts": "4.0.3",

I used Tutorial https://www.drupal.org/project/js_component for my **theme** (not module).

I have 2 components as react apps that I want to import, header and footer. When I implement only one of them, the component is shown. But when I Implement both, only the second one is shown. 

This is my `foo.js_component.yml`, only the footer is shown instead of both:
```
header:
  label: Header react app
  root_id: header
  libraries:
    js:
      /styleguide/components/header/static/js/2.06ff3371.chunk.js: { } # vendor code
      /styleguide/components/header/static/js/3.de884f23.chunk.js: { } # vendor code
      /styleguide/components/header/static/js/main.d0fcf0b5.chunk.js: { } # component code
      /styleguide/components/header/static/js/runtime-main.90901547.js: { } # webpack runtime logic
footer:
  label: Footer react app
  root_id: footer
  libraries:
    js:
#      /styleguide/components/footer/static/js/2.06ff3371.chunk.js: { } # not needed again
#      /styleguide/components/footer/static/js/3.de884f23.chunk.js: { } # not needed again
      /styleguide/components/footer/static/js/main.7ea391ec.chunk.js: { }
#      /styleguide/components/footer/static/js/runtime-main.90901547.js: { } # not needed again
```

Blocks:
<img width="714" alt="blocks" src="https://user-images.githubusercontent.com/4472725/140733910-616b297a-adb4-4091-b935-2f82b0d2a7ea.PNG">

Any ideas?

**EDIT**

When I copy the module variant example that has 2 prepared react apps (https://github.com/AtenDesignGroup/js_component_examples/tree/master/custom_module_example), both prepared react apps are shown. But still, my own components dont show up simultaneously, it is the same phenomena, only the second app is shown. I also tried with new clean react apps created with create-react-app ("react": "^17.0.2", "react-dom": "^17.0.2", "react-scripts": "4.0.3").

```
header:
  label: Header
  root_id: header
  libraries:
    js:
      /components/header/static/js/2.chunk.js: { }
      /components/header/static/js/3.chunk.js: { }
      /components/header/static/js/main.chunk.js: { }
      /components/header/static/js/runtime-main.js: { }

footer:
  label: Footer
  root_id: footer
  libraries:
    js:
      /data/footer.js: { }
      /components/footer/static/js/2.chunk.js: { }
      /components/footer/static/js/3.chunk.js: { }
      /components/footer/static/js/main.chunk.js: { }
      /components/footer/static/js/runtime-main.js: { }
```
